import org.scalatest.funsuite.AnyFunSuite
import org.scalatest.matchers.should.Matchers
import upickle.default._

class MapBuilderTest extends AnyFunSuite with Matchers {

  test("JSON parsing handles missing fields as empty strings if converter does so") {
    // We expect the JSON to be generated by XlsxConverter which ensures no nulls.
    // But if we test deserialization from a sample string, we must match what XlsxConverter writes.
    // XlsxConverter writes "" for nulls.

    val json = """[
      {
        "name": "Test",
        "pdf_url": "",
        "slug": "test",
        "url": "http://test.com",
        "venueAddress": "123 Main St",
        "latitude": 40.0,
        "longitude": -74.0,
        "summary": "Summary",
        "website": "",
        "collections": "",
        "borough": "Manhattan",
        "neighborhood": "Chelsea",
        "primaryCategory": "Food",
        "primaryLocation": "NYC",
        "restaurantInclusionWeek": "Week 1",
        "image_url": "",
        "partnerId": 123,
        "meal_type": "$30 Lunch",
        "tags": "Italian"
      }
    ]"""

    val restaurants = read[List[Restaurant]](json)
    println(s"Size: ${restaurants.size}")
    if (restaurants.nonEmpty) {
        val r = restaurants.head
        println(s"Head: $r")
    }

    restaurants should have size 1
    restaurants.head.name shouldBe "Test"
    restaurants.head.pdf_url shouldBe ""
    restaurants.head.website shouldBe ""
  }

  test("HTML generation contains map initialization and links") {
    val r = Restaurant(
        name = "Test Restaurant",
        pdf_url = "",
        slug = "test",
        url = "http://test.com",
        venueAddress = "123 Main St",
        latitude = 40.0,
        longitude = -74.0,
        summary = "Summary",
        website = "http://web.site",
        collections = "",
        borough = "Manhattan",
        neighborhood = "Chelsea",
        primaryCategory = "Food",
        primaryLocation = "NYC",
        restaurantInclusionWeek = "Week 1",
        image_url = "",
        partnerId = ujson.Num(123),
        meal_type = "$30 Lunch",
        tags = "Italian"
    )

    val html = MapBuilder.generateHtml(List(r))
    html should include("L.map(\"map\"")
    html should include("google.com/maps/search")
    html should include("yelp.com/search")
    html should include("resy.com/cities/ny")
    html should include("Test+Restaurant")
  }

  test("Direct links override search links") {
    val r = Restaurant(
        name = "Test Restaurant",
        pdf_url = "",
        slug = "test",
        url = "http://test.com",
        venueAddress = "123 Main St",
        latitude = 40.0,
        longitude = -74.0,
        summary = "Summary",
        website = "",
        collections = "",
        borough = "Manhattan",
        neighborhood = "Chelsea",
        primaryCategory = "Food",
        primaryLocation = "NYC",
        restaurantInclusionWeek = "Week 1",
        image_url = "",
        partnerId = ujson.Num(123),
        meal_type = "$30 Lunch",
        tags = "Italian",
        resy_url = "https://resy.com/direct",
        google_maps_url = "https://google.com/maps/direct",
        yelp_url = "https://yelp.com/direct"
    )

    val html = MapBuilder.generateHtml(List(r))
    html should include("https://resy.com/direct")
    html should include("https://google.com/maps/direct")
    html should include("https://yelp.com/direct")

    // Should NOT include search links for this restaurant
    html should not include("google.com/maps/search")
    html should not include("yelp.com/search")
    // resy default link search is just query=name.
    html should not include("resy.com/cities/ny?query=")
  }
}
